### ISSUE TITLE
TS exception into web_socket.d.ts

### ISSUE THREAD

**Issue by mxmind** [michel-kraemer/vertx-lang-typescript#2]
Error:(74, 13) TS2403: Subsequent variable declarations must have the same type.  Variable 'WebSocket' must be of type '{ new (url: string, protocols?: string): WebSocket; new (url: string, protocols?: string[]): WebS...', but here has type 'new () => WebSocket'.

**Comment by michel-kraemer** [comment]
Can you please provide a reproducer? I mean a small project that demonstrates the problem? Or a small TypeScript verticle and how you run it.

Thanks,
Michel

**Comment by michel-kraemer** [comment]
@mxmind Are you still interested in a fix? Please let me know if I can help.

**Comment by mxmind** [comment]
Hi, sorry for late response. At this moment, my team is concentrated on
release. I'll ask someone to prepare small project to depict the issue.
16 груд. 2015 9:03 пп "Michel Krämer" notifications@github.com пише:

**Comment by jmiller101** [comment]
Hi there @michel-kraemer I'm having this same issue. I was following this guide: http://vertx.io/blog/ecmascript-6-7-on-the-jvm-with-typescript-and-vert-x/

I'm on OS X El Capitan, compiling with TypeScript 1.7.3 (bundled with IntelliJ Idea 15). I'm using version 1.1.0 of the "typings".

Here is the file that I am compiling:

```
/// <reference path="../resources/vertx-lang-typescript-1.1.0-typings/vertx-js/vertx.d.ts"/>

// arrow functions ********************************************* [1]
vertx.createHttpServer().requestHandler(request => {
  // block-scoped variables (let keyword) ********************** [2]
  let response = request.response();
  response.setChunked(true);

  // default parameter ***************************************** [3]
  function send(msg = "NOOP") {
    response.write(msg);
  }
  send();
  send("\n");

  // rest parameters ******************************************* [4]
  function sendMulti(...messages) {
    messages.forEach(msg => response.write(msg));
  }
  sendMulti("Hello", " ", "World", "\n");

  // spread parameters ***************************************** [5]
  let messages = ["Foo", "Bar", "\n"];
  sendMulti(...messages);

  // for...of loop ********************************************* [6]
  let arr = ["1", "+", "1", "=", "2", "\n"];
  for (let v of arr) {
    send(v);
  }

  // multi-line template strings, string interpolation ********* [7]
  let name = "Elvis";
  send(`${name} lives`);

  // classes *************************************************** [8]
  class Animal {
    eat() {
      send("Animal is eating\n");
    }
  }

  class Dog extends Animal {
    eat() {
      send("Dog is eating\n");
    }

    walk() {
      send("Dog is walking\n");
    }
  }

  class Bird extends Animal {
    eat() {
      super.eat();
      send("Animal is a bird\n");
    }

    fly() {
      send("Bird is flying\n");
    }
  }

  let dog = new Dog();
  let bird = new Bird();
  dog.eat();
  dog.walk();
  bird.eat();
  bird.fly();

  // exponentiation operator *********************************** [9]
  let i = 5 ** 2;
  send("" + i);
  send("\n");

  response.end();
}).listen(8080);
```

Here is the error I get when compiling:

> Error:(84, 13) TS2403: Subsequent variable declarations must have the same type.  Variable 'WebSocket' must be of type '{ new (url: string, protocols?: string | string[]): WebSocket; prototype: WebSocket; CLOSED: numb...', but here has type '{}'.

The error appears to originate from line 84-85 of web_socket.d.ts:

```
declare var WebSocket: {
}
```

I'm fairly new to TypeScript in general so this could be a configuration issue on my end, but I figured since there was a previous similar issue I'd comment here while I poke around myself.

**Comment by michel-kraemer** [comment]
I'll reopen this issue and have a look at your code later today. I'll get back to you.

**Comment by michel-kraemer** [comment]
You didn't do anything wrong. Your example should work. Can you please test again with the latest snapshot 1.2.0-SNAPSHOT? I just fixed an issue that only occurred on Mac. Maybe the latest snapshot fixes your problem too.

https://oss.sonatype.org/content/repositories/snapshots/de/undercouch/vertx-lang-typescript/1.2.0-SNAPSHOT/

**Comment by michel-kraemer** [comment]
... or maybe we are talking about different things here. When I first read your post I was under the impression you were using the java part of vertx-lang-typescript but now, after going through it again, it seems you're only using the typings and trying to compile the TypeScript file directly (maybe inside IntelliJ or with the tsc command) instead of letting Vert.x do this for you. Is this correct?

If so, please call the TypeScript compiler with the `--noLib` flag (see all compiler flags on the TypeScript website [1]). This will omit the default definition of `WebSocket`, although it will also omit everything else from the TypeScript standard library. If you need the standard library, include the minimal version (without the browser-related stuff) in your typescript file like this:

```
/// <reference path="path_to_typescript_compiler/lib/lib.core.d.ts"/>
```

Hope this helps!
Michel

[1] http://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by jmiller101** [comment]
Thanks for the quick turn around, hopefully I'll have time to test this before lunch. I'll keep you updated.

**Comment by jmiller101** [comment]
> ... or maybe we are talking about different things here. When I first read your post I was under the impression you were using the java part of vertx-lang-typescript but now, after going through it again, it seems you're only using the typings and trying to compile the TypeScript file directly (maybe inside IntelliJ or with the tsc command) instead of letting Vert.x do this for you. Is this correct?

Geez I must not be getting enough sleep. This was the issue! Thank you for the help. I'm getting a different error now but I think I can figure it out.

**Comment by michel-kraemer** [comment]
Thanks for confirming this. It might help other users running into the same issue.

Just for the record: the problem is that the TypeScript compiler uses the standard library with all the browser definitions by default, even though it is executed on the server side. Unfortunately, there's nothing I can do in vertx-lang-typescript to work around this.
